### ISSUE TITLE
Storyteller is allowed to vote

### ISSUE THREAD

**Issue by Megaleo** [Megaleo/dixit-telegram-bot#20]
# Description
On May 20, 13:10 BRT, I was the storyteller and I voted in a card using inline. A message "Leonardo Lessa is impatient..." appeared, but my vote was counted. When Thomas voted, `n-1` players voted, including me. Hence, the game crashed, expecting that all the other players to have had voted, but Carol hadn't voted yet. The log:
```
2022-05-19 09:16:17,904 - INFO - Stage 3: Vote!
2022-05-19 09:17:54,896 - INFO - Inline - Mateus, card_id: 237
2022-05-19 09:17:54,896 - INFO - Table - (1/7) votes
2022-05-19 09:19:17,238 - INFO - Inline - Gabriel, card_id: 12
2022-05-19 09:19:17,239 - INFO - Table - (2/7) votes
2022-05-19 09:20:01,193 - INFO - Inline - Marina, card_id: 172
2022-05-19 09:20:01,194 - INFO - Table - (3/7) votes
2022-05-19 09:26:14,505 - INFO - Inline - Marcelo, card_id: 217
2022-05-19 09:26:14,506 - INFO - Table - (4/7) votes
2022-05-19 09:37:07,066 - INFO - Inline - Karina, card_id: 299
2022-05-19 09:37:07,067 - INFO - Table - (5/7) votes
2022-05-20 12:10:35,231 - INFO - Inline - Leonardo, card_id: 121
2022-05-20 12:10:35,231 - INFO - Table - (6/7) votes
2022-05-20 12:13:43,281 - INFO - Inline - Thomas, card_id: 217
2022-05-20 12:13:43,281 - INFO - Table - (7/7) votes

2022-05-20 12:13:43,282 - INFO - Stage 0: Lobby!
2022-05-20 12:13:43,283 - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/megaleo/miniconda3/envs/dixit/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/megaleo/miniconda3/envs/dixit/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/home/megaleo/Documents/scripts/Python scripts/dixit-telegram-bot/utils.py", line 162, in msg_f
    return f(update, context, *args, **kwargs)
  File "/home/megaleo/Documents/scripts/Python scripts/dixit-telegram-bot/main.py", line 328, in inline_choices
    end_of_round(update, context)
  File "/home/megaleo/Documents/scripts/Python scripts/dixit-telegram-bot/main.py", line 388, in end_of_round
    vote = results.votes[player] if not is_st else None
KeyError: Player(name=Carol, id_=1766083452)
```

# Explanation
The impatient message was sent because `inline_callback` detected that I am the storyteller, however `inline_choices` didn't and sent my vote to `dixit_game.storyteller_turn`:
https://github.com/Megaleo/dixit-telegram-bot/blob/e019624e69bed6a4221fc0ac9f927b9bd26244e6/main.py#L281-L287

# Possible fix
Include a check on `inline_choices` or in `storyteller_turn`. I don't know which would be best.

**Comment by gb-solis** [comment]
Caused by commit `d50d5735`
